version: '3'
services:
  router:
    build: 
      context: ./router
      dockerfile: Dockerfile_router
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      - c-r
      - s-r

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile_client
    command: 
      - "/bin/sleep"
      - "infinity"  
    networks:
      - c-r     

  server_:
    image: node:16.20.0-alpine3.18
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      - s-r

networks:
  c-r: {}
  s-r: {}
