version: '3'
services:
  router:
    build: 
      context: ./router
      dockerfile: Dockerfile_router
    #set the network and system priviledges high to make it possible to add static route and set the flag for forwarding to 1. Done for all the containers in this primal phase.
    cap_add:
      - NET_ADMIN
    privileged: true
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      c-r:
        ipv4_address: 172.16.1.2
      s-r:
        ipv4_address: 172.16.0.2

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile_client
    cap_add:
      - NET_ADMIN
    privileged: true
    command: 
      - "/bin/sleep"
      - "infinity"  
    networks:
      c-r:
        ipv4_address: 172.16.1.10
  temp:
    build: 
      context: ./temp
      dockerfile: Dockerfile_temp
    cap_add:
      - NET_ADMIN
    privileged: true
    command: 
      - "/bin/sleep"
      - "infinity"  
    networks:
      s-r:
        ipv4_address: 172.16.0.11
  server_:
    image: ubuntu:22.04
    command:
      #- "ip route add 172.16.1.0/24 via 172.16.0.2" 
      - "/bin/sleep"
      - "infinity"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      s-r:
        ipv4_address: 172.16.0.10

networks:
  c-r:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
  s-r:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
