FROM ubuntu:22.04

# Run the command to install the required packages. This command adds a layer to the image.
RUN apt-get update
RUN apt-get install -y iputils-ping && apt-get install -y iproute2 iptables socat

RUN apt-get install -y git make g++ automake autoconf libtool pip

RUN apt-get install -y git libssl-dev libev-dev libevent-dev build-essential
#RUN rm -rf /var/lib/apt/lists/*
    
RUN git clone https://github.com/shekyan/slowhttptest.git

# Change working directory to slowhttptest
WORKDIR /slowhttptest

# Configure and build slowhttptest
RUN ./configure && \
    make && \
    make install

# Cleanup unnecessary files
RUN rm -rf /slowhttptest

# Set the working directory back to the root directory
WORKDIR /

RUN git clone https://github.com/Hyperclaw79/HULK-v3.git

WORKDIR /HULK-v3

RUN pip install -r requirements_linux.txt

WORKDIR /

RUN apt-get install socat

COPY entrypoints/ep_attacker.sh entrypoints/ep_attacker.sh


#make the scripts executable 
RUN chmod +x /entrypoints/ep_attacker.sh 

CMD ["/bin/bash"]
