FROM ubuntu:22.04

#
RUN apt-get update

# Install ip utils
RUN apt-get install -y iputils-ping && apt-get install -y iproute2 iptables socat

# These libraries are usefull to install slowhttptest and hulk
RUN apt-get install -y git make g++ automake autoconf libtool pip
RUN apt-get install -y git libssl-dev libev-dev libevent-dev build-essential

# Install slowhttptest
RUN git clone https://github.com/shekyan/slowhttptest.git
WORKDIR /slowhttptest
RUN ./configure && \
    make && \
    make install
RUN rm -rf /slowhttptest

# Set the working directory back to the root directory
WORKDIR /

# Install HULK
RUN git clone https://github.com/Hyperclaw79/HULK-v3.git
WORKDIR /HULK-v3
RUN pip install -r requirements_linux.txt
WORKDIR /



# Copy andmake the scripts executable 
COPY entrypoints/ep_attacker.sh entrypoints/ep_attacker.sh
RUN chmod +x /entrypoints/ep_attacker.sh 

CMD ["/bin/bash"]
