FROM ubuntu:22.04

# Run the command to install the required packages
RUN apt-get update && apt-get install -y  && apt-get install -y iproute2 iptables coreutils iputils-ping syslog-ng 

   
RUN apt-get install -y apt-transport-https ca-certificates curl clang llvm jq && \
apt-get install -y libelf-dev libpcap-dev libbfd-dev binutils-dev build-essential make && \
apt-get install -y linux-tools-common && \
apt-get install -y bpfcc-tools && \
apt-get install -y python3-pip


RUN apt-get install -y nodejs npm

RUN git clone https://github.com/libbpf/libbpf && \
cd libbpf/src && \
make && \
make install && \
cd ../..

RUN git clone --recurse-submodules https://github.com/libbpf/bpftool.git && \
    cd bpftool/src && \
    make install && \
    cd ../..

RUN apt-get install nodejs npm

COPY ./server/package.json /app/package.json
COPY ./server/server.js	/app/server.js	
WORKDIR /app

RUN npm install

EXPOSE 3000 

WORKDIR /

   
COPY entrypoints/ep_servidor.sh entrypoints/ep_servidor.sh

#make the scripts executable 
RUN chmod +x /entrypoints/ep_servidor.sh


CMD ["/bin/bash"]




