FROM ubuntu:22.04

# Run the command to install the required packages
RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y iproute2 coreutils iptables nodejs npm syslog-ng
   
RUN apt-get install -y apt-transport-https ca-certificates curl clang llvm jq && \
    apt-get install -y libelf-dev libpcap-dev libbfd-dev binutils-dev build-essential make && \
    apt-get install -y linux-tools-common && \
    apt-get install -y bpfcc-tools && \
    apt-get install -y python3-pip && \

CMD ["/bin/bash"]




